### ISSUE TITLE
Plugin not being recognized not loading when i /plugins

### ISSUE THREAD

**Issue by SavageDatBoi** [vincss/mcEmptyServerStopper#1]
other plugins are working even sleeping server is working just not the server stopper im on version 1.16.5 please help ive doing this for 4 hours.

**Comment by vincss** [comment]
Which version are you using ?
Did you unzip the .zip to get a .jar and put it plugins/?

**Comment by disgusteddog** [comment]
I second this ^. Ive tried running on 1.16.5 server stopper on my server and it just wouldn't load. Im currently running at 1.16.5. The past serverstopper (1.15.2) works just fine with my 1.16.5 server though.

**Comment by vincss** [comment]
Hi !
That weird, are you sure you unziped the file and put the jar into plugins ?
Which version of MC Server are you using ?

**Comment by disgusteddog** [comment]
Yup, I put the jar file in the plugins folder and the version that I'm running is 1.16.5

**Comment by vincss** [comment]
Are you using a special flavor or Minecraft Server ? Spigot, Paper, ... ?

**Comment by disgusteddog** [comment]
My server runs on paper and the os is on the latest version of windows 10.

**Comment by vincss** [comment]
I don't understand, I tested it on exactly the same configuration, and it's working just fine 
![image](https://user-images.githubusercontent.com/2254806/113549511-dea5d900-95f1-11eb-888d-492118d36712.png)

**Comment by disgusteddog** [comment]
I kept getting this Java error so I decided to update java from java 8 to java16 and that fixed the issue!
![Screenshot 2021-04-05 131904](https://user-images.githubusercontent.com/76534618/113606966-ad8bcf80-9616-11eb-95ee-517eef7514de.jpg)
 Thanks for the help!

**Comment by vincss** [comment]
Thanks for the information, I will put in onto the wiki page.

**Comment by disgusteddog** [comment]
Hey can you add this to the wiki for those who don't want to go through the hassle of going through the manual installation of java 16. https://adoptopenjdk.net/?variant=openjdk16&jvmVariant=hotspot

**Comment by vincss** [comment]
For now, I think java 11 is the current LTS.
