### ISSUE TITLE
Timer isn't stopped when a player joins

### ISSUE THREAD

**Issue by canthisbe** [vincss/mcEmptyServerStopper#11]
Title. For example, last player leaves, starting the hour timer. Someone could join right after but the timer would still be running. That player leaves right before the timer is done, then voila, the server is shutdown despite it being inactive for way less than an hour. Having it so the timer is cancelled when someone joins would be better than checking for a player once the timer is done.

**Comment by vincss** [comment]
Yes, I already notice that but didn't happen that much, so I kept it that way.
Maybe I will try to cancel the timer when someone connect.

**Comment by vincss** [comment]
Hi,
I made a new release, you can give it a try : 
https://github.com/vincss/mcEmptyServerStopper/releases/tag/v1.1.0

**Comment by canthisbe** [comment]
Hey, sorry for late response! I've used it and it has worked flawlessly, thank you! Forgot to mention this, but in the previous release, when it detected empty again, it would just create another timer instead of resetting the previous, so multiple timers would run and each timer would check on their respective end. The new release also fixed that issue inherently.
