### ISSUE TITLE
Shutdown after player leaves

### ISSUE THREAD

**Issue by BorisP1234** [vincss/mcEmptyServerStopper#16]
Hi, When a player from my server logs of the server shuts down. How can I make it so that goes back to sleep?

**Comment by BorisP1234** [comment]
Oops forgot to say: Hi,

**Comment by BorisP1234** [comment]
Forgot to tell that I am using the fabric version because I am running a Fabric server

**Comment by vincss** [comment]
How do you launch the server ? Can you show me the settings and logs of the mcsleepingserverstarter ?

**Comment by BorisP1234** [comment]
> 
Hi, I made a video to show you how I start the server. It is using bungeecord (waterfall). But I think it is meant to shut down after a player leaves (that's what the plugin is for of course) so it is more of a suggestion that it would be nice to have an option that when a player leaves, the server goes back to sleep instead of it to shut down. 

This is the sleepingsettings file:

serverName: SleepingServer, waiting for his prince...
serverPort: 25569
maxPlayers: 2
loginMessage: Waking server up, please wait a minute
serverOnlineMode: false
webPort: 0
webStopOnStart: false
startMinecraft: true
minecraftCommand: java -Xmx10G -jar fabric.jar nogui
version: false


https://github.com/vincss/mcEmptyServerStopper/assets/132673559/a3256ce8-81a4-421f-8123-7841123e5fb3

**Comment by BorisP1234** [comment]
Just saw it working again. I think it sometimes shuts down after a couple hours of someone playing. I will send a screenshot when it happens.

**Comment by vincss** [comment]
Hi,
If the server is launched trough https://github.com/vincss/mcsleepingserverstarter , I don't see why it doesn't go to sleep.
Do you have the log of mcsleepingserverstarter when the server shuts down ?

**Comment by vincss** [comment]
@BorisP1234 
Any news ?

**Comment by BorisP1234** [comment]
thought i already closed this issue because i don't use the plugin anymore. i will close the issue now 👍
