### ISSUE TITLE
Added configuration

### ISSUE THREAD

**Issue by Asguho** [vincss/mcEmptyServerStopper#19]
Is it possible to add a configuration file where you can change the duration, in minutes, before the server shuts down after the last player leaves?

**Comment by vincss** [comment]
Hi,
There is already ShutdownTimeInMinutes in .\plugins\EmptyServerStopper\config.yml

**Comment by Asguho** [comment]
Oh sorry forgot to specify that I am using the fabric mod. Is there still a way to configure the timer?

**Comment by vincss** [comment]
Hi,
It's in another repo, and there is already a issue on this one :
https://github.com/GHYAKIMA/emptyserverstopper-mod/issues/2
