### ISSUE TITLE
Server stays on when friends forget to join the server. 

### ISSUE THREAD

**Issue by disgusteddog** [vincss/mcEmptyServerStopper#2]
Can you make the server stopper plugin auto turn off the server even if no one has joined? Sometimes my friends start the server but then go do some other tasks and don't actually join the server. When this happens the server just stays open and the plugin doesnt activate. Can you please add a feature to fix this? Thanks! :)

**Comment by vincss** [comment]
Hi !
It's already the case, there is a parameter in the config file 
plugins/EmptyServerStopper/config.yml
And change ShutdownAtStart .

**Comment by disgusteddog** [comment]
Ok okay sorry for not double checking.
