### ISSUE TITLE
Bug: Timer not starting without joining

### ISSUE THREAD

**Issue by Flo2410** [vincss/mcEmptyServerStopper#21]
If I start my Paper server, but nobody joins it, the timer is not started. I would expect the server to stop automatically, even without someone needing to join. 
Maybe you could start the timer on plugin activation/server start.

**Comment by vincss** [comment]
Hi, 
There is a setting for that in the configuration file : 
".\plugins\EmptyServerStopper\config.yml".  => ShutdownAtStart

**Comment by Flo2410** [comment]
Thanks!
I feel so stupid that I missed that...

**Comment by vincss** [comment]
I edited the readme hopes it will be more clear that way. ;-)
