### ISSUE TITLE
1.17.1 support?

### ISSUE THREAD

**Issue by PigR1** [vincss/mcEmptyServerStopper#3]
Will you be updating this for 1.17.1?

**Comment by vincss** [comment]
It should be working as it is. Do you have an error message or something ?

**Comment by vincss** [comment]
I re-tested it and it's working fine.
I released a new version for more comptabilities, can you check it ?

**Comment by Lunarnight1** [comment]
i am trying to use the Spigot/Bukkit server setup for 1.17.1 how can i do that?

**Comment by vincss** [comment]
Hi !
Do you have a specific question ?
You can check the README of SleepingServer : 
https://github.com/vincss/mcsleepingserverstarter

Come back if you have any questions !

**Comment by dada513** [comment]
for me 1.17.1 and 1.18 work fine, spigot has good  backward compatibility
