### ISSUE TITLE
Directly release jar, and not archive

### ISSUE THREAD

**Issue by dada513** [vincss/mcEmptyServerStopper#4]
Would be nice for automation not having to unzip
I am preparing a PufferPanel template for sleeping server starter. This would allow me to download from your repo directly and not from my fork that has direct jar in release

**Comment by vincss** [comment]
Hi !
I added the .jar to the latest release, is it ok for you like this ? 
https://github.com/vincss/mcEmptyServerStopper/releases/tag/v1.0.0

**Comment by dada513** [comment]
yes exactly thanks

**Comment by vincss** [comment]
Can you link the template when it's done ? Thanks :-)

**Comment by dada513** [comment]
> Can you link the template when it's done ? Thanks :-)

yes i'll PR the JSON of the template to sleeping server starter repo for users to easily find it
