### ISSUE TITLE
Forge version?

### ISSUE THREAD

**Issue by SLDDL** [vincss/mcEmptyServerStopper#7]
There is currently no mod to stop automatically a server if no one is connected.

**Comment by vincss** [comment]
Hi !
Thanks for the suggestion it would require some investigation.
I never used Forge and don't know how plugins work for it.

**Comment by Jannik44** [comment]
heyy, i would also really apprechiate a forge version as mod ;)

**Comment by vincss** [comment]
Hi ,
Forge & Fabrik versions have been made : 
https://github.com/GHYAKIMA/emptyserverstopper-mod/releases
