### ISSUE TITLE
Docker

### ISSUE THREAD

**Issue by WarrioR151** [vincss/mcEmptyServerStopper#9]
Hello, can you tell me please how can i make so when user create server in pterodactyl (i have hosting) this plugin, with folder preconfigured willl automatically regenerate (create) on every reset start? (So users can't delete or edit it)? Someone told me i need to make new Docker image, but i don't know how, never worked with docker, also i don't understand the tutorials, can i get your help with this? :/

**Comment by vincss** [comment]
Hi !
I think you can give pterodactyl with mcsleepingserverstarter a try :
https://github.com/vincss/mcsleepingserverstarter#-pterodactyl

**Comment by vincss** [comment]
No news. Closing.
